sudo: required
services:
  - docker

before_install: 
  - docker build -t dockerdev011/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerdev011/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-Section-07"
  env: "Docker-Section-07-env"
  bucket_name: "elasticbeanstalk-us-east-1-684949456108"
  docker_path: "Docker-Section-07" 
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
